In [1]:
import sqlite3 as sqlite

connection = sqlite.connect('example.db')
cursor = connection.cursor()

In [2]:
cursor.execute('''
               CREATE TABLE IF NOT EXISTS USERS(
                id integer primary key autoincrement,
                name text not null,
                email text not null unique,
                gender varchar(10) not null,
                created_at datetime default current_timestamp,
                updated_at datetime default current_timestamp            
               )
               ''')
connection.commit()

In [5]:
cursor.execute('''
               insert into users (name,email,gender) values ('Salman Riaz','salman992912@gmail.com','male')
               ''')
connection.commit()

In [9]:
import pandas as pd

cursor.execute('''SELECT* from users''')
rows = cursor.fetchall()
df = pd.DataFrame(rows, columns=['id', 'name', 'email', 'gender', 'created_at', 'updated_at'])
df

,id,name,email,gender,created_at,updated_at
0,1,Rehan Riaz,rehan5383@gmail.com,male,2026-05-12 16:10:52,2026-05-12 16:10:52
1,2,Salman Riaz,salman992912@gmail.com,male,2026-05-12 16:11:19,2026-05-12 16:11:19

In [12]:
data = [{"name":'John Doe', "email":'john.doe@example.com', "gender":'male'},
        {"name":'Jane Smith', "email":'jane.smith@example.com', "gender":'female'},
        {"name":'Alice Johnson', "email":'alice.johnson@example.com', "gender":'female'},
        {"name":'Bob Brown', "email":'bob.brown@example.com', "gender":'male'}]

cursor.executemany('''
                   insert into users (name,email,gender) values (:name, :email, :gender)
                   ''', data)

connection.commit()

In [ ]:
cursor.execute('''SELECT* from users''')
columns = [description[0] for description in cursor.description]
rows = cursor.fetchall()
df = pd.DataFrame(rows, columns=columns)

,id,name,email,gender,created_at,updated_at
0,1,Rehan Riaz,rehan5383@gmail.com,male,2026-05-12 16:10:52,2026-05-12 16:10:52
1,2,Salman Riaz,salman992912@gmail.com,male,2026-05-12 16:11:19,2026-05-12 16:11:19
2,3,John Doe,john.doe@example.com,male,2026-05-12 16:18:01,2026-05-12 16:18:01
3,4,Jane Smith,jane.smith@example.com,female,2026-05-12 16:18:01,2026-05-12 16:18:01
4,5,Alice Johnson,alice.johnson@example.com,female,2026-05-12 16:18:01,2026-05-12 16:18:01
5,6,Bob Brown,bob.brown@example.com,male,2026-05-12 16:18:01,2026-05-12 16:18:01

In [16]:
cursor.execute('''UPDATE users set name="Rehan Riaz Ahmad" where id = 1''')
connection.commit()

In [18]:
cursor.execute('''SELECT* from users''')
columns = [description[0] for description in cursor.description]
rows = cursor.fetchall()
df = pd.DataFrame(rows, columns=columns)
df

,id,name,email,gender,created_at,updated_at
0,1,Rehan Riaz Ahmad,rehan5383@gmail.com,male,2026-05-12 16:10:52,2026-05-12 16:10:52
1,2,Salman Riaz,salman992912@gmail.com,male,2026-05-12 16:11:19,2026-05-12 16:11:19
2,3,John Doe,john.doe@example.com,male,2026-05-12 16:18:01,2026-05-12 16:18:01
3,4,Jane Smith,jane.smith@example.com,female,2026-05-12 16:18:01,2026-05-12 16:18:01
4,5,Alice Johnson,alice.johnson@example.com,female,2026-05-12 16:18:01,2026-05-12 16:18:01
5,6,Bob Brown,bob.brown@example.com,male,2026-05-12 16:18:01,2026-05-12 16:18:01

In [38]:
cursor.execute('''UPDATE users SET name = ?, gender = ? WHERE id = ?''', ["Amna Riaz", "female", 2])

connection.commit()

In [41]:
cursor.execute('''SELECT* from users''')
columns = [description[0] for description in cursor.description]
rows = cursor.fetchall()
df = pd.DataFrame(rows, columns=columns)
df

,id,name,email,gender,created_at,updated_at
0,1,Rehan Riaz Ahmad,rehan5383@gmail.com,male,2026-05-12 16:10:52,2026-05-12 16:10:52
1,2,Amna Riaz,salman992912@gmail.com,female,2026-05-12 16:11:19,2026-05-12 16:11:19
2,4,Jane Smith,jane.smith@example.com,female,2026-05-12 16:18:01,2026-05-12 16:18:01
3,5,Alice Johnson,alice.johnson@example.com,female,2026-05-12 16:18:01,2026-05-12 16:18:01
4,6,Bob Brown,bob.brown@example.com,male,2026-05-12 16:18:01,2026-05-12 16:18:01

In [40]:
cursor.execute('''DELETE from users where id = ?''', [3])
connection.commit()