In [54]:
import pandas as pd
#series
series = pd.Series([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(series)

0       [1, 2, 3, 4, 5, 6]
1    [7, 8, 9, 10, 11, 12]
dtype: object

In [3]:
import pandas as pd

series_dic = pd.Series({'a':1,'b':2,'c':3,'d':4})
print(series_dic)

a    1
b    2
c    3
d    4
dtype: int64

In [4]:
data = [1,2,3,4]
indexes = ['a','b','c','d']

series_with_indexes = pd.Series(data,index=indexes)
print(series_with_indexes)

a    1
b    2
c    3
d    4
dtype: int64

In [5]:
df = pd.DataFrame([{'name':'Rehan','age':32,'address':'Gujranwala'},{'name':'Salman Riaz','age':21,'address':'Austria'}])
print(df)

          name  age     address
0        Rehan   32  Gujranwala
1  Salman Riaz   21     Austria

In [10]:
#from csv
df = pd.read_csv("sales_data.csv")
df.head(5)

,Order_ID,Date,Product,Category,Price,Quantity,Payment_Method
0,ORD-10001,2025-05-14,MacBook Air M2,Laptop,396538,5,JazzCash
1,ORD-10002,2025-05-07,Sony WH-1000XM5,Accessories,94182,1,EasyPaisa
2,ORD-10003,2025-05-19,iPhone 15,Mobile,321269,4,JazzCash
3,ORD-10004,2026-01-16,Airpods Pro,Accessories,51859,5,Credit Card
4,ORD-10005,2025-07-02,Airpods Pro,Accessories,58606,2,Credit Card

In [60]:
df.loc[1]['Product']

'Sony WH-1000XM5'

In [61]:
df.iloc[1]

Order_ID           ORD-10003
Date              2025-05-19
Product            iPhone 15
Category              Mobile
Price                 321270
Quantity                   4
Payment_Method      JazzCash
Name: 2, dtype: object

In [13]:
df['Date']

0       2025-05-14
1       2025-05-07
2       2025-05-19
3       2026-01-16
4       2025-07-02
           ...
4995    2025-11-29
4996    2025-09-15
4997    2025-06-06
4998    2025-06-25
4999    2026-03-02
Name: Date, Length: 5000, dtype: str

In [19]:
df.head(2)

,Order_ID,Date,Product,Category,Price,Quantity,Payment_Method
0,ORD-10001,2025-05-14,MacBook Air M2,Laptop,396538,5,JazzCash
1,ORD-10002,2025-05-07,Sony WH-1000XM5,Accessories,94182,1,EasyPaisa

In [25]:
print(df.loc[0]['Date'])
print(df.iloc[0]['Product'])

2025-05-14
MacBook Air M2

In [27]:
df.head(2)

,Order_ID,Date,Product,Category,Price,Quantity,Payment_Method
0,ORD-10001,2025-05-14,MacBook Air M2,Laptop,396538,5,JazzCash
1,ORD-10002,2025-05-07,Sony WH-1000XM5,Accessories,94182,1,EasyPaisa

In [28]:
df.at[1,'Product']

'Sony WH-1000XM5'

In [29]:
df.iat[1,2]

'Sony WH-1000XM5'

In [30]:
df['is_active'] = 1

In [31]:
df

,Order_ID,Date,Product,Category,Price,Quantity,Payment_Method,is_active
0,ORD-10001,2025-05-14,MacBook Air M2,Laptop,396538,5,JazzCash,1
1,ORD-10002,2025-05-07,Sony WH-1000XM5,Accessories,94182,1,EasyPaisa,1
2,ORD-10003,2025-05-19,iPhone 15,Mobile,321269,4,JazzCash,1
3,ORD-10004,2026-01-16,Airpods Pro,Accessories,51859,5,Credit Card,1
4,ORD-10005,2025-07-02,Airpods Pro,Accessories,58606,2,Credit Card,1
...,...,...,...,...,...,...,...,...
4995,ORD-14996,2025-11-29,iPhone 15,Mobile,320392,4,Cash,1
4996,ORD-14997,2025-09-15,Airpods Pro,Accessories,54518,2,EasyPaisa,1
4997,ORD-14998,2025-06-06,Samsung S24,Mobile,234107,3,JazzCash,1
4998,ORD-14999,2025-06-25,iPhone 15,Mobile,303658,5,EasyPaisa,1
4999,ORD-15000,2026-03-02,Dell XPS 13,Laptop,362826,1,Cash,1

In [35]:
df['is_active'] =  1

In [36]:
df.head(2)

,Order_ID,Date,Product,Category,Price,Quantity,Payment_Method,is_active
0,ORD-10001,2025-05-14,MacBook Air M2,Laptop,396538,5,JazzCash,1
1,ORD-10002,2025-05-07,Sony WH-1000XM5,Accessories,94182,1,EasyPaisa,1

In [43]:
df.drop('is_active',axis=1,inplace=True)

In [44]:
df

,Order_ID,Date,Product,Category,Price,Quantity,Payment_Method
0,ORD-10001,2025-05-14,MacBook Air M2,Laptop,396538,5,JazzCash
1,ORD-10002,2025-05-07,Sony WH-1000XM5,Accessories,94182,1,EasyPaisa
2,ORD-10003,2025-05-19,iPhone 15,Mobile,321269,4,JazzCash
3,ORD-10004,2026-01-16,Airpods Pro,Accessories,51859,5,Credit Card
4,ORD-10005,2025-07-02,Airpods Pro,Accessories,58606,2,Credit Card
...,...,...,...,...,...,...,...
4995,ORD-14996,2025-11-29,iPhone 15,Mobile,320392,4,Cash
4996,ORD-14997,2025-09-15,Airpods Pro,Accessories,54518,2,EasyPaisa
4997,ORD-14998,2025-06-06,Samsung S24,Mobile,234107,3,JazzCash
4998,ORD-14999,2025-06-25,iPhone 15,Mobile,303658,5,EasyPaisa
4999,ORD-15000,2026-03-02,Dell XPS 13,Laptop,362826,1,Cash

In [45]:
df['Price'] = df['Price']+1

In [46]:
df.head(2)

,Order_ID,Date,Product,Category,Price,Quantity,Payment_Method
0,ORD-10001,2025-05-14,MacBook Air M2,Laptop,396539,5,JazzCash
1,ORD-10002,2025-05-07,Sony WH-1000XM5,Accessories,94183,1,EasyPaisa

In [49]:
df.drop(0,inplace=True)

In [50]:
df

,Order_ID,Date,Product,Category,Price,Quantity,Payment_Method
1,ORD-10002,2025-05-07,Sony WH-1000XM5,Accessories,94183,1,EasyPaisa
2,ORD-10003,2025-05-19,iPhone 15,Mobile,321270,4,JazzCash
3,ORD-10004,2026-01-16,Airpods Pro,Accessories,51860,5,Credit Card
4,ORD-10005,2025-07-02,Airpods Pro,Accessories,58607,2,Credit Card
5,ORD-10006,2025-07-01,Sony WH-1000XM5,Accessories,103491,1,Cash
...,...,...,...,...,...,...,...
4995,ORD-14996,2025-11-29,iPhone 15,Mobile,320393,4,Cash
4996,ORD-14997,2025-09-15,Airpods Pro,Accessories,54519,2,EasyPaisa
4997,ORD-14998,2025-06-06,Samsung S24,Mobile,234108,3,JazzCash
4998,ORD-14999,2025-06-25,iPhone 15,Mobile,303659,5,EasyPaisa
4999,ORD-15000,2026-03-02,Dell XPS 13,Laptop,362827,1,Cash

In [51]:
df.describe()

               Price     Quantity
count    4999.000000  4999.000000
mean   199188.620724     2.974395
std    123058.769368     1.416526
min     10007.000000     1.000000
25%     64442.500000     2.000000
50%    231567.000000     3.000000
75%    306219.000000     4.000000
max    399905.000000     5.000000

In [68]:
import numpy as np

array = np.arange(1,11)
print(array)

[ 1  2  3  4  5  6  7  8  9 10]

In [73]:
df[df['Price'] > 5000]

,Order_ID,Date,Product,Category,Price,Quantity,Payment_Method
1,ORD-10002,2025-05-07,Sony WH-1000XM5,Accessories,94183,1,EasyPaisa
2,ORD-10003,2025-05-19,iPhone 15,Mobile,321270,4,JazzCash
3,ORD-10004,2026-01-16,Airpods Pro,Accessories,51860,5,Credit Card
4,ORD-10005,2025-07-02,Airpods Pro,Accessories,58607,2,Credit Card
5,ORD-10006,2025-07-01,Sony WH-1000XM5,Accessories,103491,1,Cash
...,...,...,...,...,...,...,...
4995,ORD-14996,2025-11-29,iPhone 15,Mobile,320393,4,Cash
4996,ORD-14997,2025-09-15,Airpods Pro,Accessories,54519,2,EasyPaisa
4997,ORD-14998,2025-06-06,Samsung S24,Mobile,234108,3,JazzCash
4998,ORD-14999,2025-06-25,iPhone 15,Mobile,303659,5,EasyPaisa
4999,ORD-15000,2026-03-02,Dell XPS 13,Laptop,362827,1,Cash

In [75]:
df.shape

(4999, 7)

In [82]:
df[(df['Category'] == 'Mobile') & (df['Price'] >= 90000)]

,Order_ID,Date,Product,Category,Price,Quantity,Payment_Method
2,ORD-10003,2025-05-19,iPhone 15,Mobile,321270,4,JazzCash
6,ORD-10007,2026-03-22,iPhone 15,Mobile,309389,4,Cash
9,ORD-10010,2025-08-01,Google Pixel 8,Mobile,219518,1,Credit Card
10,ORD-10011,2025-04-19,Samsung S24,Mobile,257692,2,Credit Card
16,ORD-10017,2025-08-31,iPhone 15,Mobile,269899,1,Cash
...,...,...,...,...,...,...,...
4991,ORD-14992,2025-09-16,Samsung S24,Mobile,284859,5,Credit Card
4994,ORD-14995,2026-01-25,Google Pixel 8,Mobile,214874,3,JazzCash
4995,ORD-14996,2025-11-29,iPhone 15,Mobile,320393,4,Cash
4997,ORD-14998,2025-06-06,Samsung S24,Mobile,234108,3,JazzCash
4998,ORD-14999,2025-06-25,iPhone 15,Mobile,303659,5,EasyPaisa

In [84]:
df.query("Price >= 90000 and Category=='Mobile'")

,Order_ID,Date,Product,Category,Price,Quantity,Payment_Method
2,ORD-10003,2025-05-19,iPhone 15,Mobile,321270,4,JazzCash
6,ORD-10007,2026-03-22,iPhone 15,Mobile,309389,4,Cash
9,ORD-10010,2025-08-01,Google Pixel 8,Mobile,219518,1,Credit Card
10,ORD-10011,2025-04-19,Samsung S24,Mobile,257692,2,Credit Card
16,ORD-10017,2025-08-31,iPhone 15,Mobile,269899,1,Cash
...,...,...,...,...,...,...,...
4991,ORD-14992,2025-09-16,Samsung S24,Mobile,284859,5,Credit Card
4994,ORD-14995,2026-01-25,Google Pixel 8,Mobile,214874,3,JazzCash
4995,ORD-14996,2025-11-29,iPhone 15,Mobile,320393,4,Cash
4997,ORD-14998,2025-06-06,Samsung S24,Mobile,234108,3,JazzCash
4998,ORD-14999,2025-06-25,iPhone 15,Mobile,303659,5,EasyPaisa